apiVersion: v1
kind: Service 
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None 

--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress-mysql
  labels: 
    app: wordpress-statefulset
spec:
  selector:
    matchLabels:
      app: wordpress-statefulset
      tier: mysql
  replicas: 1
  serviceName: wordpress-statefulset-mysql
  template:
    metadata:
      labels: 
        app: wordpress-statefulset
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
          name: mysql  
      volumes: 
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim      
  volumeClaimTemplates:
  - metadata:
      name: wordpress-statefulset-mysql
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: statefull